name: "push"
version: "0.1.5"
usage: "Please see https://github.com/Cheneytt/helm-push for usage"
description: "Push chart package to Nexus"
command: "$HELM_PLUGIN_DIR/bin/helmpush"

hooks:
  install: "cd $HELM_PLUGIN_DIR && chmod +x ./scripts/install.sh && ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR && chmod +x ./scripts/install.sh && ./scripts/install.sh"
