name: "push"
version: "0.1.0"
usage: "Please see https://github.com/Cheneytt/helm-push for usage"
description: "Push chart package to Nexus"
command: "$HELM_PLUGIN_DIR/bin/helmpush"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
